name: Build Optimized Windows EXE

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Build optimized EXE
      run: poetry run pyinstaller --onefile --windowed --name=EmailFinder --clean --noupx --noconfirm main.py

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: EmailFinder-Optimized
        path: dist/EmailFinder.exe