name: Build Windows EXE

on:
  push:
    tags: [ 'v*' ] # Запускать сборку при пуше новых тегов, например v1.0.0
  workflow_dispatch: # Позволяет запускать сборку вручную из интерфейса GitHub

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated from v3

      - name: Set up Python
        uses: actions/setup-python@v5 # Updated from v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Build EXE with PyInstaller
        run: poetry run pyinstaller --onefile --windowed --name=EmailFinder --clean main.py

      - name: Upload EXE as an artifact
        uses: actions/upload-artifact@v4 # Updated from v3
        with:
          name: EmailFinder-Windows 
          path: dist/EmailFinder.exe